spring:
  application:
    name: pessoa-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-api}:${DB_PORT:5432}/pessoa_api
    username: ${DB_USER:dev}
    password: ${DB_PASS:dev}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    baseline-on-migrate: true

server:
  port: 8081

logging:
  level:
    org.springframework: INFO
