spring:
  application:
    name: pessoa-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-web}:${DB_PORT:5432}/pessoa_web
    username: ${DB_USER:dev}
    password: ${DB_PASS:dev}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    baseline-on-migrate: true
  rabbitmq:
    host: ${MQ_HOST:rabbitmq}
    port: ${MQ_PORT:5672}
  web:
    locale: pt_BR
    locale-resolver: fixed

server:
  port: 8080

logging:
  level:
    org.springframework: INFO